# Generated by Django 5.2.3 on 2025-06-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
